### ISSUE TITLE
Panic on run

### ISSUE THREAD

**Issue by yuriizinets** [nore-dev/fman#15]
First of all, awesome work!
As a developer, I love it when the work is praised, and this is the case.

After installation with `go install` and running, I've got this:

```bash
> fman

Caught panic:

runtime error: index out of range [0] with length 0

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
	/Users/yuriizinets/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.1/tea.go:370 +0x8c
panic({0x1011bcec0, 0x140003a02b8})
	/opt/homebrew/Cellar/go/1.19.1/libexec/src/runtime/panic.go:890 +0x258
github.com/nore-dev/fman/model.ListModel.View({{0x140000c0000, 0x3a, 0x47}, {0x1400012a1c8, 0x12}, 0x52, 0x27, 0x0, 0x140000de000, 0x1d, ...})
	/Users/yuriizinets/go/pkg/mod/github.com/nore-dev/fman@v1.15.0/model/list.go:397 +0x1da4
main.(*App).View(0x140000e0000)
	/Users/yuriizinets/go/pkg/mod/github.com/nore-dev/fman@v1.15.0/main.go:84 +0xd8
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0x140000e4000)
	/Users/yuriizinets/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.1/tea.go:541 +0xfb4
github.com/charmbracelet/bubbletea.(*Program).Start(...)
	/Users/yuriizinets/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.1/tea.go:548
main.main()
	/Users/yuriizinets/go/pkg/mod/github.com/nore-dev/fman@v1.15.0/main.go:128 +0x624
```

Some additional information:
- Machine: Macbook Air M1
- System: MacOS Monterey (12.6)
- Shell: bash

**Comment by nore-dev** [comment]
Thank you for creating an issue. I will try to fix it

**Comment by nore-dev** [comment]
@yuriizinets Can you install the latest version and tell me if the problem still exists?

**Comment by yuriizinets** [comment]
Everything works, thank you! :)
