### ISSUE TITLE
Error on folders above home path

### ISSUE THREAD

**Issue by nore-dev** [nore-dev/fman#7]
It works fine under /home directory but for example, if you go to /usr directory it gives an error.

```
Caught panic:

stat lib: no such file or directory

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
        /usr/lib/go/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /home/noredev/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.1/tea.go:370 +0x95
panic({0x7cb520, 0xc00009a090})
        /usr/lib/go/src/runtime/panic.go:890 +0x262
github.com/nore-dev/fman/model.ListModel.Update({{0xc000153b00, 0xd, 0x10}, {0xc0000162b8, 0x16}, 0x0, 0x0, 0x0, 0xc000072c80, 0x0, ...}, ...)
        /home/noredev/dev/fman/model/list.go:178 +0x11fc
main.(*App).Update(0xc000324000, {0x7cc5a0?, 0xc000321a20})
        /home/noredev/dev/fman/main.go:66 +0x4aa
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc00011e160)
        /home/noredev/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.1/tea.go:539 +0x12bf
github.com/charmbracelet/bubbletea.(*Program).Start(...)
        /home/noredev/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.22.1/tea.go:548
main.main()
        /home/noredev/dev/fman/main.go:124 +0x77f
```

**Comment by dzzzchhh** [comment]
Hey, really like the looks of `fman`, just tried it and for me this also occurs in random places - sometime it doesn't have to be `home`, just a couple of attempts of trying to go up the directory tree.

**Comment by nore-dev** [comment]
@dzzzchhh Sorry for this problem. I will try to fix all these bugs as soon as possible

**Comment by dzzzchhh** [comment]
No worries, @nore-dev, I'll also try to look into it :)

**Comment by nore-dev** [comment]
@dzzzchhh  Can you install the latest version and tell me if the problem still exists?

**Comment by dzzzchhh** [comment]
Works like a charm now, @nore-dev, thanks!

**Comment by nore-dev** [comment]
Thank you @dzzzchhh
